    define('kbpaths', [], function(paths) {
        requirejs.config({
            baseUrl : 'src/kbsrc/widgets',
            urlArgs: "bust=" + (new Date()).getTime(),
            paths : {
                'jquery'      : '../../../ext/jquery/jquery-1.10.2.min',
                'jqueryui'    : '../../../ext/jquery-ui/1.10.3/js/jquery-ui-1.10.3.custom.min',
                'bootstrap'   : "../../../ext/bootstrap/3.3.0/js/bootstrap.min",
                'd3'          : "../../../ext/d3/d3.v3.min",
                'colorbrewer' : "../../../ext/colorbrewer/colorbrewer",
                'handlebars'  : '../../../ext/handlebars/handlebars-v1.3.0',
				'RGBColor'                          : '../js/RGBColor',
				'geometry_point'                    : '../js/geometry/geometry_point',
				'geometry_rectangle'                : '../js/geometry/geometry_rectangle',
				'geometry_size'                     : '../js/geometry/geometry_size',
				'kbapplication'                     : '../kbapplication',
				'kbwidget'                          : '../kbwidget',
				'all'                               : '../widgets/all',
				'kbaseIrisTerminalDispatch'         : '../widgets/iris/config/kbaseIrisTerminalDispatch',
				'kbaseIrisTerminalDispatchAuth'     : '../widgets/iris/config/kbaseIrisTerminalDispatchAuth',
				'kbaseIrisTerminalDispatchEnv'      : '../widgets/iris/config/kbaseIrisTerminalDispatchEnv',
				'kbaseIrisTerminalDispatchFile'     : '../widgets/iris/config/kbaseIrisTerminalDispatchFile',
				'kbaseIrisTerminalDispatchHelp'     : '../widgets/iris/config/kbaseIrisTerminalDispatchHelp',
				'kbaseIrisTerminalDispatchHistory'  : '../widgets/iris/config/kbaseIrisTerminalDispatchHistory',
				'kbaseIrisTerminalDispatchScript'   : '../widgets/iris/config/kbaseIrisTerminalDispatchScript',
				'kbaseIrisTerminalDispatchTutorial' : '../widgets/iris/config/kbaseIrisTerminalDispatchTutorial',
				'iris'                              : '../widgets/iris/iris',
				'kbaseIrisCommands'                 : '../widgets/iris/kbaseIrisCommands',
				'kbaseIrisConfig'                   : '../widgets/iris/kbaseIrisConfig',
				'kbaseIrisContainerWidget'          : '../widgets/iris/kbaseIrisContainerWidget',
				'kbaseIrisEchoWidget'               : '../widgets/iris/kbaseIrisEchoWidget',
				'kbaseIrisFileBrowser'              : '../widgets/iris/kbaseIrisFileBrowser',
				'kbaseIrisFileEditor'               : '../widgets/iris/kbaseIrisFileEditor',
				'kbaseIrisGUIWidget'                : '../widgets/iris/kbaseIrisGUIWidget',
				'kbaseIrisGrammar'                  : '../widgets/iris/kbaseIrisGrammar',
				'kbaseIrisProcessList'              : '../widgets/iris/kbaseIrisProcessList',
				'kbaseIrisTerminal'                 : '../widgets/iris/kbaseIrisTerminal',
				'kbaseIrisTerminalWidget'           : '../widgets/iris/kbaseIrisTerminalWidget',
				'kbaseIrisTextWidget'               : '../widgets/iris/kbaseIrisTextWidget',
				'kbaseIrisTutorial'                 : '../widgets/iris/kbaseIrisTutorial',
				'kbaseIrisWhatsNew'                 : '../widgets/iris/kbaseIrisWhatsNew',
				'kbaseIrisWidget'                   : '../widgets/iris/kbaseIrisWidget',
				'kbaseIrisWorkspace'                : '../widgets/iris/kbaseIrisWorkspace',
				'kbaseAccordion'                    : '../widgets/kbaseAccordion',
				'kbaseBox'                          : '../widgets/kbaseBox',
				'kbaseButtonControls'               : '../widgets/kbaseButtonControls',
				'kbaseCarousel'                     : '../widgets/kbaseCarousel',
				'kbaseDataBrowser'                  : '../widgets/kbaseDataBrowser',
				'kbaseDeletePrompt'                 : '../widgets/kbaseDeletePrompt',
				'kbaseErrorPrompt'                  : '../widgets/kbaseErrorPrompt',
				'kbaseFormBuilder'                  : '../widgets/kbaseFormBuilder',
				'kbaseJSONReflector'                : '../widgets/kbaseJSONReflector',
				'kbasePrompt'                       : '../widgets/kbasePrompt',
				'kbaseSearchControls'               : '../widgets/kbaseSearchControls',
				'kbaseTable'                        : '../widgets/kbaseTable',
				'kbaseTabs'                         : '../widgets/kbaseTabs',
				'kbaseVisWidget'                    : '../widgets/kbaseVisWidget',
				'kbaseWalkablePath'                 : '../widgets/kbaseWalkablePath',
				'kbaseBarchart'                     : '../widgets/vis/kbaseBarchart',
				'kbaseChordchart'                   : '../widgets/vis/kbaseChordchart',
				'kbaseCircularHeatmap'              : '../widgets/vis/kbaseCircularHeatmap',
				'kbaseForcedNetwork'                : '../widgets/vis/kbaseForcedNetwork',
				'kbaseHeatmap'                      : '../widgets/vis/kbaseHeatmap',
				'kbaseHistogram'                    : '../widgets/vis/kbaseHistogram',
				'kbaseLineSerieschart'              : '../widgets/vis/kbaseLineSerieschart',
				'kbaseLinechart'                    : '../widgets/vis/kbaseLinechart',
				'kbasePiechart'                     : '../widgets/vis/kbasePiechart',
				'kbaseScatterplot'                  : '../widgets/vis/kbaseScatterplot',
				'kbaseTreechart'                    : '../widgets/vis/kbaseTreechart',
				'kbaseVenndiagram'                  : '../widgets/vis/kbaseVenndiagram',
				'kbasePlantsNTO'                    : '../widgets/vis/plants/kbasePlantsNTO',
				'kbasePlantsNetworkNarrative'       : '../widgets/vis/plants/kbasePlantsNetworkNarrative',
				'kbasePlantsNetworkTable'           : '../widgets/vis/plants/kbasePlantsNetworkTable',
				'vis'                               : '../widgets/vis/vis',
            },
            shim : {
                bootstrap : {deps : ["jquery"]}
            }
        });
    });
